"""Adapter boundary (spec §2a). The core talks only to these Protocols."""
from __future__ import annotations
from typing import AsyncIterator, Protocol, runtime_checkable
from pineforge_live import types as T
from pineforge_live import ADAPTER_API_VERSION

@runtime_checkable
class Clock(Protocol):
    def now_ms(self) -> int: ...
    def venue_now_ms(self) -> int: ...
    def skew_ms(self) -> int: ...
    async def sleep_until(self, ms: int) -> None: ...
    def timeout(self, ms: int) -> int: ...

@runtime_checkable
class InstrumentSource(Protocol):
    async def resolve(self, instrument: T.InstrumentId) -> T.EngineSyminfo: ...

@runtime_checkable
class BarSource(Protocol):
    async def history(self, instrument: T.InstrumentId, tf: str, start_ms: int, end_ms: int) -> tuple[list[T.NormalizedBar], bool]:
        """(bars, completeness) — completeness False when the venue reports a hole."""
    def events(self, instrument: T.InstrumentId, tf: str) -> AsyncIterator[T.BarEvent]: ...

@runtime_checkable
class TickSource(Protocol):
    def subscribe(self, instrument: T.InstrumentId, from_seq: int) -> AsyncIterator[T.TickEvent]: ...

@runtime_checkable
class Executor(Protocol):
    async def submit(self, action: T.OrderAction) -> T.OrderState: ...
    async def cancel(self, client_id: str | None, venue_order_id: str | None) -> T.OrderState: ...
    async def open_orders(self, instrument: T.InstrumentId) -> list[T.OrderState]: ...
    async def lookup(self, client_id: str | None, venue_order_id: str | None) -> T.OrderState | None: ...
    async def orders_since(self, instrument: T.InstrumentId, cursor: str | None) -> tuple[list[T.OrderState], str]: ...
    async def fills_since(self, instrument: T.InstrumentId, cursor: str | None) -> tuple[list[T.Fill], str]: ...
    def events(self) -> AsyncIterator[T.AccountEvent]: ...
    async def position(self, instrument: T.InstrumentId) -> float: ...
    async def account(self) -> T.AccountState: ...
    async def constraints(self, instrument: T.InstrumentId) -> T.VenueConstraints: ...

@runtime_checkable
class Adapter(Protocol):
    def capabilities(self) -> T.Capabilities: ...
    instruments: InstrumentSource
    bars: BarSource
    ticks: TickSource | None
    executor: Executor | None
    clock: Clock
